
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    env_file:
      - .env  # Cargar las variables de entorno desde .env
    ports:
      - "3000:3000"
    depends_on:
      - db  # Asegura que el contenedor db esté listo antes de iniciar la app
    networks:
      - app_network

  db:
    image: postgres:13  # Usa la imagen oficial de PostgreSQL
    container_name: rankingdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rankingdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # Volumen para persistir los datos de la base de datos
    networks:
      - app_network

volumes:
  db_data:  # Volumen para guardar los datos persistentes de PostgreSQL

networks:
  app_network:
    driver: bridge
